from rasterio.env import GDALVersion as GDALVersion, ensure_env as ensure_env, require_gdal_version as require_gdal_version
from typing import Any

blacklist: Any

def raster_driver_extensions(): ...
def driver_from_extension(path): ...
def is_blacklisted(name, mode): ...
