from . import options as options

def build_handler(ctx, param, value): ...
def get_maximum_overview_level(width, height, minsize: int = ...): ...
def overview(ctx, input, build, ls, rebuild, resampling) -> None: ...
